// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MessageController from "./message_controller.js"
application.register("message", MessageController)

import RoomChannelController from "./room_channel_controller.js"
application.register("room-channel", RoomChannelController)

import ScrollController from "./scroll_controller.js"
application.register("scroll", ScrollController)
